services:
  dev:
    build: .
    ports:
      - "5173:5173"
    volumes:
      - ./curiosity-ui:/app/curiosity-ui
      - ./demo:/app/demo
    working_dir: /app/demo
    environment:
      - NODE_ENV=development